version: 2

models:

  - name: loans_raw
    description: "Raw loan dataset ingested from CSV"

    columns:

      - name: listingkey
        description: "Unique listing identifier"
        tests:
          - not_null
          - unique

      - name: loanoriginalamount
        description: "Original loan amount"
        tests:
          - not_null

      - name: loanstatus
        description: "Current status of the loan"
        tests:
          - not_null

      - name: borrowerapr
        description: "Annual percentage rate"