project:
  name: loan_data_platform
  environment: dev

database:
  host: aws-1-ap-northeast-2.pooler.supabase.com
  port: 6543
  name: postgres
  user: postgres.ujfpsufiirzpaswgnpsx
  password: "nhungcaubedeptrai"
  pool_size: 5
  max_overflow: 10
  pool_recycle: 1800

paths:
  raw_data: data/raw/prosperLoanData.csv

schemas:
  bronze: bronze
  silver: silver
  gold: gold

tables:
  raw_loans: prosper_loans_raw

ingestion:
  chunk_size: 10000
